name: Greet Person

on:
  workflow_dispatch:
    inputs:
      person:
        description: "Person's name"
        required: true
        default: "Anon"

      language:
        description: "Language"
        required: true
        type: choice
        options:
          - "en"
          - "fr"
        default: "en"

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
          echo "Hello ${{ github.event.inputs.person }}" > output.txt

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: greeting-result-en
          path: output.txt

  say_bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: |
          echo "Hello ${{ github.event.inputs.person }}" > output.txt

      - name: Archive artifact
        uses: actions/upload-artifact@v3
        with:
          name: greeting-result-fr
          path: output.txt

  display:
    runs-on: ubuntu-latest
    needs: [say_hello, say_bonjour]
    steps: 
      - name: Download greeting
        uses: actions/download-artifact@v3
        with:
          name: greeting-result-${{github.event.inputs.language}}
        

